# parent structure handle child contenttypes
parenttype: structures
# possibles child contenttypes
contenttypes: [ structures, pages, blogposts, publications, pressreleases, events, projects, jobs, persons, taskforces ]
