# google search api docs https://developers.google.com/custom-search/docs/

client: google-csbe
cx: 009775384710117617031:r4qwwnlya8s
output: xml_no_dtd
template: listing_search.twig

results_per_page: 10
max_autocompletions: 5


