main:
    slug: main
    singular_slug: main
    behaves_like: grouping
    options: [toplevel1, toplevel2, toplevel3, toplevel4]
    has_sortorder: false
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    listing_template: listing_tags.twig
chapters:
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    options: { main: 'The main chapter', sub: 'Meta Chapter', subsub: 'The other stuff' }
    has_sortorder: true
blogs:
    # these are needed for the blogpost content type and are filtered in listing.twig
    slug: blogs
    singular_slug: blog
    behaves_like: grouping
    has_sortorder: false
    options:
        europeana-blog: 'Europeana Blog'
        europeana-cloud-blog: 'Europeana Cloud Blog'
        heritage-in-motion-blog: 'Heritage in Motion Blog'
        #europeana-test-blog: 'Europeana Test Blog'
        #europeana-creative-blog: 'Europeana Creative Blog'
        europeana-fashion: 'Europeana Fashion Blog'
        europeana-enduser: 'Europeana Enduser Blog'
        europeana-1418: 'Europeana 1914 - 1918'
