main:
    slug: main
    singular_slug: main
    behaves_like: grouping
    options: [toplevel1, toplevel2, toplevel3, toplevel4]
    has_sortorder: false
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    listing_template: listing_tags.twig
tree:
    slug: tree
    singular_slug: tree
    behaves_like: grouping
    options:
        about-us: 'About us'
        careers: 'Careers'
        contribute: 'Contribute'
        edm-case-studies: 'EDM Case studies'
        europeana-cloud: 'Europeana Cloud'
        europeana-cloud-blog: 'Europeana Cloud Blog'
        europeana-cloud-events: 'Europeana Cloud events'
        europeana-creative: 'Europeana Creative'
        europeana-creative-blog: 'Europeana Creative Blog'
        europeana-creative-events: 'Europeana Creative Events'
        europeana-tech: 'Europeana Tech'
        europeana-tech-events: 'Europeana Tech events'
        europeana-tech-task-forces: 'Europeana Tech Task forces'
        get-involved: 'Get involved'
        our-network: 'Our Network'
        partners: 'Partners'
        pilots: 'Pilots'
        press: 'Press'
        press-releases: 'Press releases'
        project-list: 'Project list'
        projects: 'Projects'
        share-your-data: 'Provide your data'
        staff: 'Staff'
        task-forces: 'Task forces'
        technical-requirements: 'Technical requirements'
        use-our-data: 'Use our data'
    multiple: false
    has_sortorder: true
chapters:
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    options: { main: 'The main chapter', sub: 'Meta Chapter', subsub: 'The other stuff' }
    has_sortorder: true
