# This file defines the different types of taxonomies in Bolt. See the 
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

    
main: 
    slug: main
    singular_slug: main
    behaves_like: grouping
    options: [ toplevel1, toplevel2, toplevel3, toplevel4 ]
    has_sortorder: false

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags

structures:
    slug: structures
    singular_slug: structure
    behaves_like: grouping
    options: { get-involved: "Get involved", europeana-network: "Europeana Network", projects: "Projects", task-forces: "Task Forces", europeana-tech: "Europeana Tech", share-your-data: "Share your data", technical-requirements: "Technical Requirements", legal-requirents: "Legal requirents",  use-our-data: "Use our data", about-us: "About us", staff: "Staff", press: "Press", pressreleases: "Press releases", join-the-network: "Join the Network" }
    has_sortorder: true
    
chapters:
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    options: { main: "The main chapter", sub: "Meta Chapter", subsub: "The other stuff" }
    has_sortorder: true
