#sitewide:
#    enabled: true
#    feed_records: 10
#    feed_template: rss.twig
#    content_length: 0
#    content_types: [entries, pages]

events: 
  enabled: true
  feed_records: 10
  feed_template: rss.twig
  content_length: 0

jobs: 
  enabled: true
  feed_records: 10
  feed_template: rss.twig
  content_length: 0

publications: 
  enabled: true
  feed_records: 10
  feed_template: rss.twig
  content_length: 0

pressreleases: 
  enabled: true
  feed_records: 10
  feed_template: rss.twig
  content_length: 0

blogposts: 
  enabled: true
  feed_records: 10
  feed_template: rss.twig
  content_length: 0
