#
# gerneral settings
#

# parent contenttype
parenttype: structures
# child contenttypes
contenttypes: [ pages, blogposts, publications, pressreleases, events, projects, taskforces, jobs, persons]

#
# sitemap settings
#
sitemap:
  sources:
    source_1:
      menu: 'primary'
    source_2:
      label: 'More info'
      data:
        blog:
          label: 'Blog'
          link: '/blogposts'
        publications:
          label: 'Publications'
          link: '/publications'
        events:
          label: 'Events'
          link: '/events'
        jobs:
          label: 'Jobs'
          link: '/jobs'
        about:
          label: 'About Us'
          data: 'about-us'
        press:
          label: 'Press'
          data: 'press'
    source_3:
      label: 'Explore Europeana'
      data:
        search_portal:
          label: 'Search Portal'
          link: '#'
        labs:
          label: Labs'
          link: '#'
        1914-1918:
          label: '1914-1918'
          link: '#'
        end_user_blog:
          label: 'End user blog'
          link: '#'
  contenttypes: ['structures', 'pages']
  template: 'sitemap.twig'
  xml_template: 'sitemap_xml.twig'
  
  